---
title: "Resultados y Diagnósticos-INLA-ST"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(sp)
library(sf)
library(gridExtra)
library(INLA)
library(latex2exp)
```

Carga de resultados:
```{r}
load('results_INLA_ST0_draft.RData')
```

Densidades posteriores de Betas fijos
```{r}
base_grafico_betas <- bind_rows(data.frame(m.ex2$marginals.fixed$intercept,type='beta0'))
#                                data.frame(m.ex2$marginals.fixed$OMEGA,type='beta1'),
#                                data.frame(m.ex2$marginals.fixed$U,type='beta2'),
#                                data.frame(m.ex2$marginals.fixed$V,type='beta3'))

ggplot(data = base_grafico_betas,mapping = aes(x = x,y = y)) + geom_line()+
  theme_bw()+facet_wrap(vars(type),nrow = 2,scales = 'free')
```

Densidades posteriores de parámetros de rango:
```{r}
outputPC1.field <- inla.spde2.result(inla=m.ex2,
                                   name="idx.PC0", spde=spde.spatial.vcm, do.transf=TRUE)
#outputPC2.field <- inla.spde2.result(inla=m.ex2,
#                                   name="idx.PC2", spde=spde.spatial.vcm, do.transf=TRUE)
#outputPC3.field <- inla.spde2.result(inla=m.ex2,
#                                   name="idx.PC3", spde=spde.spatial.vcm, do.transf=TRUE)

base_grafico_rangos <- bind_rows(data.frame(outputPC1.field$marginals.range.nominal$range.nominal.1,type='PC0'))#,
#data.frame(outputPC2.field$marginals.range.nominal$range.nominal.1,type='PC2'),
#data.frame(outputPC3.field$marginals.range.nominal$range.nominal.1,type='PC3'))

ggplot(data = base_grafico_rangos,mapping = aes(x = x,y = y)) + geom_line()+
  theme_bw()+facet_wrap(vars(type),nrow = 2,scales = 'free')
```

Densidades posteriores de parámetros de varianza por efecto aleatorio:
```{r}
base_grafico_varianzas <- bind_rows(data.frame(outputPC1.field$marginals.variance.nominal$variance.nominal.1,type='PC0'))

#data.frame(outputPC2.field$marginals.variance.nominal$variance.nominal.1,type='PC2'),
#ata.frame(outputPC3.field$marginals.variance.nominal$variance.nominal.1,type='PC3'))

ggplot(data = base_grafico_varianzas,mapping = aes(x = x,y = y)) + geom_line()+
  theme_bw()+facet_wrap(vars(type),nrow = 2,scales = 'free')
```
Densidad posterior del efecto nugget:
```{r}
base_grafico_nugget <- data.frame(inla.tmarginal(function(x) 1/x, m.ex2$marginals.hyper$`Precision for the Gaussian observations`))

ggplot(data = base_grafico_nugget,mapping = aes(x = x,y = y)) + geom_line()+
  theme_bw()
```

Densidad posterior del parámetro autoregresivo:
```{r}
base_grafico_rho <- bind_rows(data.frame(m.ex2$marginals.hyperpar$`GroupRho for idx.PC0`,type='Rho0'))

ggplot(data = base_grafico_rho,mapping = aes(x = x,y = y)) + geom_line()+
  theme_bw()+facet_wrap(vars(type),nrow = 2,scales = 'free')
```

Gráficos de observaciones vs predicciones:
```{r}
index.pred <- inla.stack.index(stack = stk.est, tag = "est")$data
Resumen_fitted <- m.ex2$summary.fitted.values[index.pred,]
hh_sf <- hh_sf %>% bind_cols(Resumen_fitted)

#inla.qmarginal(c(0.025,0.975),m.ex2$marginals.fitted.values[[1]])

hh_sf <- hh_sf %>% rename(Yhat = mean, Ysd = sd, Ymed = `0.5quant`, 
                          Y025 = `0.025quant`, Y975 = `0.975quant`)
hh_sf <- hh_sf %>% mutate(That = exp(log(TREFHT)+Yhat), 
                          Tmed = exp(log(TREFHT)+Ymed),
                          T025 = exp(log(TREFHT)+Y025),
                          T975 = exp(log(TREFHT)+Y975),
                          TR = T975-T025)


hh_sf_03 <- hh_sf %>% filter(Year == 1999, Month == 3)

grafico1 <- ggplot(data = hh_sf_03)+geom_sf(aes(col = ts))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico2 <- ggplot(data = hh_sf_03)+geom_sf(aes(col = That))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico3 <- ggplot(data = hh_sf_03)+geom_sf(aes(col = Tmed))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)


grafico4 <- ggplot(data = hh_sf_03)+geom_sf(aes(col = TR))+
  theme_bw()+
  scale_color_distiller(type = 'seq',direction = 1)

graficos_Marzo1999 <- grid.arrange(grafico1,grafico2,grafico3,grafico4)
```

```{r}
hh_sf_06 <- hh_sf %>% filter(Year == 1999, Month == 6)

grafico1 <- ggplot(data = hh_sf_06)+geom_sf(aes(col = ts))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico2 <- ggplot(data = hh_sf_06)+geom_sf(aes(col = That))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico3 <- ggplot(data = hh_sf_06)+geom_sf(aes(col = Tmed))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)


grafico4 <- ggplot(data = hh_sf_06)+geom_sf(aes(col = TR))+
  theme_bw()+
  scale_color_distiller(type = 'seq',direction = 1)

graficos_Junio1999 <- grid.arrange(grafico1,grafico2,grafico3,grafico4)
```

```{r}
hh_sf_09 <- hh_sf %>% filter(Year == 1999, Month == 9)

grafico1 <- ggplot(data = hh_sf_09)+geom_sf(aes(col = ts))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico2 <- ggplot(data = hh_sf_09)+geom_sf(aes(col = That))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico3 <- ggplot(data = hh_sf_09)+geom_sf(aes(col = Tmed))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)


grafico4 <- ggplot(data = hh_sf_09)+geom_sf(aes(col = TR))+
  theme_bw()+
  scale_color_distiller(type = 'seq',direction = 1)

graficos_Sep1999 <- grid.arrange(grafico1,grafico2,grafico3,grafico4)
```

```{r}
hh_sf_11 <- hh_sf %>% filter(Year == 1999, Month == 11)

grafico1 <- ggplot(data = hh_sf_11)+geom_sf(aes(col = ts))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico2 <- ggplot(data = hh_sf_11)+geom_sf(aes(col = That))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)

grafico3 <- ggplot(data = hh_sf_11)+geom_sf(aes(col = Tmed))+
  theme_bw()+
  scale_color_distiller(type = 'seq',palette = 'YlOrRd',direction = 1)


grafico4 <- ggplot(data = hh_sf_11)+geom_sf(aes(col = TR))+
  theme_bw()+
  scale_color_distiller(type = 'seq',direction = 1)

graficos_Nov1999 <- grid.arrange(grafico1,grafico2,grafico3,grafico4)
```

Metricas:
```{r}
MSE_month <- hh_sf %>% filter(Year==1999) %>% mutate(dif2 = (ts-That)^2) %>%
  st_drop_geometry() %>%
  group_by(Month) %>% summarise(MSE = mean(dif2))

knitr::kable(MSE_month)
MSE_year <- hh_sf %>% mutate(dif2 = (ts-That)^2) %>%
  st_drop_geometry() %>%
  group_by(Year) %>% summarise(MSE = mean(dif2))

knitr::kable(MSE_year)
IS_month <- hh_sf %>% filter(Year==1999) %>% mutate(IS = (T975-T025)+
                   (2/0.05)*(T025-That)*(That<T025)+ 
                     (2/0.05)*(That-T975)*(That>T975)) %>%
    st_drop_geometry() %>%
  group_by(Month) %>% summarise(IS95 = mean(IS))

IS_year <- hh_sf %>% mutate(IS = (T975-T025)+
                   (2/0.05)*(T025-That)*(That<T025)+ 
                     (2/0.05)*(That-T975)*(That>T975)) %>%
    st_drop_geometry() %>%
  group_by(Year) %>% summarise(IS95 = mean(IS))

knitr::kable(IS_month)

knitr::kable(IS_year)
```

