---
title: "Reporte de simulación 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### 1. Extrating estimators statistics.

```{r}
# model <- "MRA1" # "MRA2"
# type <- "Exponential" # "Matern"
# nres <- 1
# sigma2<- 2 # 2 or 0.5
# burn <- 500


alpha <- 0.05 # 1-alpha: credibility level (IS)
# Different from Gneiting (-2 alpha: constant)
IS=function(alpha,upper,lower,y){
  N=length(y)
  ISi=rep(0,N)
  for(i in 1:N){
    #show(i)
    if(y[i]<=lower[i]){
      ISi[i]=(upper[i]-lower[i])+2/alpha*(lower[i]-y[i])
    }else{
      if(lower[i]<y[i] && y[i]<upper[i]){
        ISi[i]=(upper[i]-lower[i])
      }else{
        ISi[i]=(upper[i]-lower[i])+2/alpha*(y[i]-upper[i])
      }
    }
  }
  ISres=mean(ISi)
  ISres
}
  
  betasList<-list()
  PhisList<-list()
  tausList<-list()
  YsList<-list()
  #i <- 1 # simulation ID # from 1 to 10
for(i in 1:10){
  show(i)
  load(paste0("sim_res/chain",i,model,type,nres,"sigma2_",sigma2,".Rdata"))
  print(unlist(labels))
  print(total_time)
  #Betas
  betas <- data.frame(chain$chain_result$chain_beta[-(1:burn),])
  names(betas) <- paste0('Beta',0)
  betasList[[i]] <- rbind(colMeans(betas),
                apply(betas,MARGIN=2,quantile,probs=c(alpha/2,1-alpha/2)))

  #Phis
  Phis <- data.frame(chain$chain_result$chain_Phi[-(1:burn),])
  colnames(Phis) <- paste0('Phi')
  PhisList[[i]] <- rbind(colMeans(Phis),
                apply(Phis,MARGIN=2,quantile,probs=c(alpha/2,1-alpha/2)))

  #taus
  taus <- data.frame(chain$chain_result$chain_tau[-(1:burn)])
  colnames(taus) <- paste0('taus')
  tausList[[i]] <- rbind(colMeans(taus),
                apply(taus,MARGIN=2,quantile,probs=c(alpha/2,1-alpha/2)))

  #Ysample
  load(paste0("sim_data/dataset",i,type,nres,"sigma2_",sigma2,".Rdata"))
  Yobs<-hh$Y
  Ys <- data.frame(t(chain$Ysample)[-(1:burn),])
  names(Ys) <- paste0('Y',1:ncol(Ys))
  YsList[[i]] <- rbind(colMeans(Ys),
                apply(Ys,MARGIN=2,quantile,probs=c(alpha/2,1-alpha/2)),
                Yobs)
}

```


### 2. Extrating estimators statistics.

## beta0
```{r}
betas.real <- c(1)
parameter <- betas.real 
parameterList<- betasList 

MSE_1 <- purrr::map(1:length(parameterList),
                ~(parameterList[[.]][1,]-parameter)^2) %>%
          reduce(rbind) 

MSE <- colMeans(MSE_1);MSE
RMSE <- sqrt(MSE);RMSE
 
quantiles <- list() 
for (j in 1:length(parameter)){
quantiles[[j]] <- purrr::map(1:length(parameterList),
                ~{parameterList[[.]][2:3,j]}) %>%
          reduce(rbind) 
colnames(quantiles[[j]]) <- c('Lower','Upper')
}


map_dbl(1:length(quantiles),
    ~{IS(alpha=alpha,upper=quantiles[[.]][,1],lower=quantiles[[.]][,2],y=parameter[.])})

```

## phi
```{r}
phi.real <- c(3)
parameter <- phi.real 
parameterList<- PhisList 

MSE_1 <- purrr::map(1:length(parameterList),
                ~(parameterList[[.]][1,]-parameter)^2) %>%
          reduce(rbind) 

MSE <- colMeans(MSE_1);MSE
RMSE <- sqrt(MSE);RMSE
 
quantiles <- list() 
for (j in 1:length(parameter)){
quantiles[[j]] <- purrr::map(1:length(parameterList),
                ~{parameterList[[.]][2:3,j]}) %>%
          reduce(rbind) 
colnames(quantiles[[j]]) <- c('Lower','Upper')
}


map_dbl(1:length(quantiles),
    ~{IS(alpha=alpha,upper=quantiles[[.]][,1],lower=quantiles[[.]][,2],y=parameter[.])})

```

## tau
```{r}
tau.real <- c(1)
parameter <- tau.real 
parameterList<- tausList 

MSE_1 <- purrr::map(1:length(parameterList),
                ~(parameterList[[.]][1,]-parameter)^2) %>%
          reduce(rbind) 

MSE <- colMeans(MSE_1);MSE
RMSE <- sqrt(MSE);RMSE
 
quantiles <- list() 
for (j in 1:length(parameter)){
quantiles[[j]] <- purrr::map(1:length(parameterList),
                ~{parameterList[[.]][2:3,j]}) %>%
          reduce(rbind) 
colnames(quantiles[[j]]) <- c('Lower','Upper')
}


map_dbl(1:length(quantiles),
    ~{IS(alpha=alpha,upper=quantiles[[.]][,1],lower=quantiles[[.]][,2],y=parameter[.])})

```

### 3. Observations (Y)

```{r}
# con respecto al Y simulado en cada escenario.
MSEb <- purrr::map(1:length(YsList),~(YsList[[.]][1,]-YsList[[.]][4,])^2)
MSEb <- MSEb %>% reduce(rbind)
MSE <- colMeans(MSEb)
RMSE <- sqrt(MSE)
hist(RMSE);summary(RMSE)

quantiles <- list() 
for (j in 1:nrow(chain$Ysample)){
quantiles[[j]] <- purrr::map(1:length(YsList),
                ~{YsList[[.]][1:4,j]}) %>%
          reduce(rbind) 
colnames(quantiles[[j]]) <- c("Ymean",'Lower','Upper',"Yobs")
}

# con respecto al Y observado
ISY<-map_dbl(1:length(quantiles),
    ~{IS(alpha=alpha,upper=quantiles[[.]][,2],lower=quantiles[[.]][,3],y=quantiles[[.]][,4])})

hist(ISY)
summary(ISY)


```

